# Generated by Django 3.0.3 on 2020-02-21 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_auto_20200221_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Profile',
        ),
    ]
