# Generated by Django 3.0.3 on 2020-02-24 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0004_auto_20200221_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag_post',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='tag_post',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='category',
            name='user_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='tag_id',
            field=models.ManyToManyField(to='post.Tag'),
        ),
        migrations.DeleteModel(
            name='Cat_user',
        ),
        migrations.DeleteModel(
            name='Tag_post',
        ),
    ]
