# Generated by Django 3.0.3 on 2020-02-25 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200224_1140'),
        ('post', '0007_auto_20200224_2111'),
    ]

    operations = [
    ]
