# Generated by Django 3.0.3 on 2020-02-27 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200225_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='relay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.Comment')),
            ],
        ),
    ]
