# Generated by Django 3.0.3 on 2020-02-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20200227_1227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='relay',
        ),
    ]
