# Generated by Django 3.0.3 on 2020-02-26 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200225_0811'),
        ('landing_page', '0002_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
